export const busStopAudio = {
  stationRoad: new Audio("./StopRecordings/stationRoad.mp3"),
  winchmoreHill: new Audio("./StopRecordings/winchmoreHill.mp3"),
  shrubberyGardens: new Audio("./StopRecordings/shrubberyGardens.mp3"),
  greenDragonLane: new Audio("./StopRecordings/greenDragonLane.mp3"),
  oldParkRidings: new Audio("./StopRecordings/oldParkRidings.mp3"),
  hadleyWay: new Audio("./StopRecordings/hadleyWay.mp3"),
  bazileRoad: new Audio("./StopRecordings/bazileRoad.mp3"),
  eversleyParkRoad: new Audio("./StopRecordings/eversleyParkRoad.mp3"),
  eversleyMount: new Audio("./StopRecordings/eversleyMount.mp3"),
  churchHill: new Audio("./StopRecordings/churchHill.mp3"),
  parkGate: new Audio("./StopRecordings/parkGate.mp3"),
  queenElizabethsDrive: new Audio("./StopRecordings/queenElizabethsDrive.mp3"),
  stThomasRoad: new Audio("./StopRecordings/stThomasRoad.mp3"),
  southgateStation: new Audio("./StopRecordings/southgateStation.mp3"),
  southgatePoliceStation: new Audio(
    "./StopRecordings/southgatePoliceStation.mp3"
  ),
  southgateAsda: new Audio("./StopRecordings/southgateAsda.mp3"),
  avenueRoad: new Audio("./StopRecordings/avenueRoad.mp3"),
  manorDrive: new Audio("./StopRecordings/manorDrive.mp3"),
  hampdenSquare: new Audio("./StopRecordings/hampdenSquare.mp3"),
  osidgeLibrary: new Audio("./StopRecordings/osidgeLibrary.mp3"),
  deneRoad: new Audio("./StopRecordings/deneRoad.mp3"),
  beresfordAvenue: new Audio("./StopRecordings/beresfordAvenue.mp3"),
  pollardRoad: new Audio("./StopRecordings/pollardRoad.mp3"),
  myddeltonPark: new Audio("./StopRecordings/myddeltonPark.mp3"),
  ashcroftCourt: new Audio("./StopRecordings/ashcroftCourt.mp3"),
  whetstoneTheGriffin: new Audio("./StopRecordings/whetstoneTheGriffin.mp3"),
  whetstoneHighRoadFriernBarnetLane: new Audio(
    "./StopRecordings/whetstoneHighRoadFriernBarnetLane.mp3"
  ),
  swanLane: new Audio("./StopRecordings/swanLane.mp3"),
  derwentCrescent: new Audio("./StopRecordings/derwentCrescent.mp3"),
  finchleyPark: new Audio("./StopRecordings/finchleyPark.mp3"),
  ravensdaleAvenue: new Audio("./StopRecordings/ravensdaleAvenue.mp3"),
  torringtonPark: new Audio("./StopRecordings/torringtonPark.mp3"),
  tallyHoCorner: new Audio("./StopRecordings/tallyHoCorner.mp3"),
  woodberryGrove: new Audio("./StopRecordings/woodberryGrove.mp3"),
  granvilleRoad: new Audio("./StopRecordings/granvilleRoad.mp3"),
  victoriaPark: new Audio("./StopRecordings/victoriaPark.mp3"),
  longLane: new Audio("./StopRecordings/longLane.mp3"),
  finchleyCentralStation: new Audio(
    "./StopRecordings/finchleyCentralStation.mp3"
  ),
  dollisParkFinchleyCentralStation: new Audio(
    "./StopRecordings/dollisParkFinchleyCentralStation.mp3"
  ),
  stMarysChurch: new Audio("./StopRecordings/stMarysChurch.mp3"),
  stMarysAvenue: new Audio("./StopRecordings/stMarysAvenue.mp3"),
  ardenRoad: new Audio("./StopRecordings/ardenRoad.mp3"),
  crookedUsage: new Audio("./StopRecordings/crookedUsage.mp3"),
  broughtonAvenue: new Audio("./StopRecordings/broughtonAvenue.mp3"),
  greatNorthWay: new Audio("./StopRecordings/greatNorthWay.mp3"),
  alexandraRoad: new Audio("./StopRecordings/alexandraRoad.mp3"),
  theQuadrant: new Audio("./StopRecordings/theQuadrant.mp3"),
  churchEnd: new Audio("./StopRecordings/churchEnd.mp3"),
  greyhoundHill: new Audio("./StopRecordings/greyhoundHill.mp3"),
  rowanDrive: new Audio("./StopRecordings/rowanDrive.mp3"),
  heritageAvenue: new Audio("./StopRecordings/heritageAvenue.mp3"),
  peelCentre: new Audio("./StopRecordings/peelCentre.mp3"),
  colindaleStation: new Audio("./StopRecordings/colindaleStation.mp3"),
};
