export const busStopAudio = {
  stationRoad: new Audio("./StopRecordings/stationRoad.ogg"),
  winchmoreHill: new Audio("./StopRecordings/winchmoreHill.ogg"),
  shrubberyGardens: new Audio("./StopRecordings/shrubberyGardens.ogg"),
  greenDragonLane: new Audio("./StopRecordings/greenDragonLane.ogg"),
  oldParkRidings: new Audio("./StopRecordings/oldParkRidings.ogg"),
  hadleyWay: new Audio("./StopRecordings/hadleyWay.ogg"),
  bazileRoad: new Audio("./StopRecordings/bazileRoad.ogg"),
  eversleyParkRoad: new Audio("./StopRecordings/eversleyParkRoad.ogg"),
  eversleyMount: new Audio("./StopRecordings/eversleyMount.ogg"),
  churchHill: new Audio("./StopRecordings/churchHill.ogg"),
  parkGate: new Audio("./StopRecordings/parkGate.ogg"),
  queenElizabethsDrive: new Audio("./StopRecordings/queenElizabethsDrive.ogg"),
  stThomasRoad: new Audio("./StopRecordings/stThomasRoad.ogg"),
  southgateStation: new Audio("./StopRecordings/southgateStation.ogg"),
  southgatePoliceStation: new Audio(
    "./StopRecordings/southgatePoliceStation.ogg"
  ),
  southgateAsda: new Audio("./StopRecordings/southgateAsda.ogg"),
  avenueRoad: new Audio("./StopRecordings/avenueRoad.ogg"),
  manorDrive: new Audio("./StopRecordings/manorDrive.ogg"),
  hampdenSquare: new Audio("./StopRecordings/hampdenSquare.ogg"),
  osidgeLibrary: new Audio("./StopRecordings/osidgeLibrary.ogg"),
  deneRoad: new Audio("./StopRecordings/deneRoad.ogg"),
  beresfordAvenue: new Audio("./StopRecordings/beresfordAvenue.ogg"),
  pollardRoad: new Audio("./StopRecordings/pollardRoad.ogg"),
  myddeltonPark: new Audio("./StopRecordings/myddeltonPark.ogg"),
  ashcroftCourt: new Audio("./StopRecordings/ashcroftCourt.ogg"),
  whetstoneTheGriffin: new Audio("./StopRecordings/whetstoneTheGriffin.ogg"),
  whetstoneHighRoadFriernBarnetLane: new Audio(
    "./StopRecordings/whetstoneHighRoadFriernBarnetLane.ogg"
  ),
  swanLane: new Audio("./StopRecordings/swanLane.ogg"),
  derwentCrescent: new Audio("./StopRecordings/derwentCrescent.ogg"),
  finchleyPark: new Audio("./StopRecordings/finchleyPark.ogg"),
  ravensdaleAvenue: new Audio("./StopRecordings/ravensdaleAvenue.ogg"),
  torringtonPark: new Audio("./StopRecordings/torringtonPark.ogg"),
  tallyHoCorner: new Audio("./StopRecordings/tallyHoCorner.ogg"),
  woodberryGrove: new Audio("./StopRecordings/woodberryGrove.ogg"),
  granvilleRoad: new Audio("./StopRecordings/granvilleRoad.ogg"),
  victoriaPark: new Audio("./StopRecordings/victoriaPark.ogg"),
  longLane: new Audio("./StopRecordings/longLane.ogg"),
  finchleyCentralStation: new Audio(
    "./StopRecordings/finchleyCentralStation.ogg"
  ),
  dollisParkFinchleyCentralStation: new Audio(
    "./StopRecordings/dollisParkFinchleyCentralStation.ogg"
  ),
  stMarysChurch: new Audio("./StopRecordings/stMarysChurch.ogg"),
  stMarysAvenue: new Audio("./StopRecordings/stMarysAvenue.ogg"),
  ardenRoad: new Audio("./StopRecordings/ardenRoad.ogg"),
  crookedUsage: new Audio("./StopRecordings/crookedUsage.ogg"),
  broughtonAvenue: new Audio("./StopRecordings/broughtonAvenue.ogg"),
  greatNorthWay: new Audio("./StopRecordings/greatNorthWay.ogg"),
  alexandraRoad: new Audio("./StopRecordings/alexandraRoad.ogg"),
  theQuadrant: new Audio("./StopRecordings/theQuadrant.ogg"),
  churchEnd: new Audio("./StopRecordings/churchEnd.ogg"),
  greyhoundHill: new Audio("./StopRecordings/greyhoundHill.ogg"),
  rowanDrive: new Audio("./StopRecordings/rowanDrive.ogg"),
  heritageAvenue: new Audio("./StopRecordings/heritageAvenue.ogg"),
  peelCentre: new Audio("./StopRecordings/peelCentre.ogg"),
  colindaleStation: new Audio("./StopRecordings/colindaleStation.ogg"),
};
