export const busStops = [
  "Station Road",
  "Shrubbery Gardens",
  "Green Dragon Lane",
  "Old Park Ridings",
  "Hadley Way",
  "Bazile Road",
  "Eversley Park Road",
  "Eversley Mount",
  "Church Hill",
  "Park Gate",
  "Queen Elizabeth's Drive",
  "St Thomas Road",
  "Southgate Station",
  "Southgate Police Station",
  "Southgate Asda",
  "Avenue Road",
  "Manor Drive",
  "Hampden Square",
  "Osidge Library",
  "Dene Road",
  "Beresford Avenue",
  "Pollard Road",
  "Myddleton Park",
  "Ashcroft Court",
  "Whetstone/the Griffin",
  "Whetstone High Road/Friern Barnet Lane",
  "Swan Lane",
  "Derwent Crescent",
  "Finchley Park",
  "Ravensdale Avenue",
  "Torrington Park",
  "Tally Ho Corner",
  "Woodberry Grove",
  "Granville Road",
  "Victoria Park",
  "Long Lane",
  "Finchley Central Station",
  "Dollis Park/Finchley Central Station",
  "St Mary's Church",
  "St Mary's Avenue",
  "Arden Road",
  "Crooked Usage",
  "Broughton Avenue",
  "Great North Way",
  "Alexandra Road",
  "The Quadrant",
  "Church End",
  "Greyhound Hill",
  "Rowan Drive",
  "Heritage Avenue",
  "Peel Centre",
  "Colindale Station",
];
